version: "3.9"

services:
  bot:
    build: .
    container_name: tgbot
    working_dir: "/usr/src/app/${BOT_NAME:-tg_bot}"
    volumes:
    - .:/usr/src/app/${BOT_NAME:-tg_bot}
    command: python3 -m bot
    restart: always
    env_file:
      - ".env"
    networks:
    - tg_bot

  db:
    image: postgres:12.0-alpine
    container_name: postgres
    restart: always
    env_file: .env

    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_NAME

    ports:
      - ${DB_PORT}:5432

    volumes:
      - db_data:/var/lib/postgresql/data


volumes:
  db_data:

networks:
  tg_bot:
    driver: bridge